[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "conda_forge_ci_utils"
author = "conda-forge/core"
author-email = "conda-forge/core@github.com"
home-page = "https://conda-forge.org"
classifiers = ["License :: OSI Approved :: MIT License"]

