# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.14
  timeoutInMinutes: 360
  strategy:
    maxParallel: 8
    matrix:
      osx_python3.6.____cpython:
        CONFIG: osx_python3.6.____cpython
        UPLOAD_PACKAGES: True
      osx_python3.7.____cpython:
        CONFIG: osx_python3.7.____cpython
        UPLOAD_PACKAGES: True

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      echo "Fast Finish"


  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - script: |
      source activate base
      echo "Configuring conda."

      conda install -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build pip

      setup_conda_rc ./ "./recipe" ./.ci_support/${CONFIG}.yaml

      export CI=azure
      # Overriding global run_conda_forge_build_setup_osx with local copy.
      source recipe/run_conda_forge_build_setup_osx
      conda update --yes --quiet --override-channels -c conda-forge -c defaults --all
      conda uninstall --quiet --yes --force conda-forge-ci-setup
      RECIPE_ROOT=recipe && pip install --no-deps ${RECIPE_ROOT}/.
    env: {
      OSX_FORCE_SDK_DOWNLOAD: "1"
    }
    displayName: 'Configure conda, conda-build, and add conda-forge-ci-setup=2'

  - script: |
      echo "Mangling homebrew from Azure to avoid conflicts."
      source activate base
      /usr/bin/sudo mangle_homebrew
      /usr/bin/sudo -k
    displayName: Mangle homebrew

  - script: |
      source activate base
      mangle_compiler ./ "./recipe" ./.ci_support/${CONFIG}.yaml
    displayName: Mangle compiler

  - script: |
      source activate base
      make_build_number ./ "./recipe" ./.ci_support/${CONFIG}.yaml
    displayName: Generate build number clobber file

  - script: |
      source activate base
      conda build "./recipe" -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
    displayName: Build recipe

  - script: |
      source activate base
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      upload_package ./ "./recipe" ./.ci_support/${CONFIG}.yaml
    displayName: Upload package
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
    condition: and(succeeded(), not(eq(variables['UPLOAD_PACKAGES'], 'False')))
